name: Basic Build Workflow

on:
  push:
    branches: [jazzy, art-jazzy]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-jazzy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ros:jazzy-ros-core
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Create Workspace
      run: |
        mkdir src_tmp
        mv `find -maxdepth 1 -not -name . -not -name src_tmp` src_tmp/
        mv src_tmp/ src/
    - name: Install Prerequisites
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        apt-get update && apt-get upgrade -y && apt-get install ros-dev-tools -y && rosdep init && rosdep update; \
        rosdep install --from-paths src --ignore-src -y'
    - name: Build Workspace
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        colcon build'
    - name: Check Installed Camera Calibration Import
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        source install/setup.bash; \
        python3 -c "import camera_calibration.camera_calibrator as m; print(m.__file__); assert m.CAMERA_MODEL.FISHEYE.value == 1"'
    - name: Run Tests
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        colcon test; \
        colcon test-result --verbose'
